apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-api-gateway-server-pod
  labels:
    app: spring-api-gateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-api-gateway-server
  template:
    metadata:
      labels:
        app: spring-api-gateway-server
    spec:
      containers:
      - name: spring-api-gateway-server
        image: spring-api-gateway-server:v1
        env:
        - name: RABBIT_URI
          value: amqp://rabbitmq-service.default.svc.cluster.local:5672 
        ports:
        - containerPort: 8762
---
apiVersion: v1
kind: Service
metadata:
  name: spring-api-gateway-services
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - port: 8762
    targetPort: 8762
  selector:
    app: spring-api-gateway-server