apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-broker
  labels:
    app: kafka-broker
spec:
  serviceName: "kafka-server"
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
      - name: zoo1
        image: zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zoo1
      - name: kafka-broker
        image: sidie88/kafka:v1
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT_HOST
          value: localhost
        - name: KAFKA_ZOOKEEPER_CONNECT_PORT
          value: "2181"
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_ADVERTISED_HOST
          value: kafka-broker-0
        ports:
        - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-server
spec:
  type: NodePort
  ports:
  - port: 9092
    name: kafka-port
    protocol: TCP
  - name: zoo-client
    port: 2181
    protocol: TCP
  - name: zoo-follower
    port: 2888
    protocol: TCP
  - name: zoo-leader
    port: 3888
    protocol: TCP
  selector:
    app: kafka-broker